### ISSUE TITLE
NaNoGenMo @ Electronic Literature Organization 2016 Conference

### ISSUE THREAD

**Issue by leonardoflores** [dariusk/NaNoGenMo-2015#191]
Hi folks,

The call for proposals for the ELO 2016 conference (June 10-12, 2016 in Victoria) closes on December 6.

This is a wonderful venue to present your Generated novels, in the Media Arts Show, as a performance, as a poster presentation, individual paper, or panel.

I'm very interested in bringing this initiative and the wonderful works you've created to an academic and artistic community that appreciates generative literature. 

Please let me know if you'd like help organizing a panel or writing one or several proposals (multiple proposals welcomed) or if you have any questions.

Visit the conference website at http://elo2016.com

**Comment by cpressey** [comment]
> Please let me know [...] if you have any questions.

I have a question, regarding:

> an academic and artistic community that appreciates generative literature.

How does that work, exactly?  How do people go about appreciating generative literature?  If I wanted to improve my appreciation of generative literature, how would I do that?

I mean, if I wanted to improve my appreciation for art, there are many classes I can take, and books I can read, on art appreciation.  Is there anything comparable for generative literature, or even generative art in general?

I note that, using the DuckDuckGo search engine, I get a lot of results for ["art appreciation"](https://duckduckgo.com/?q=%22art+appreciation%22) and some for ["modern art appreciation"](https://duckduckgo.com/?q=%22modern+art+appreciation%22), but none at all for ["generative art appreciation"](https://duckduckgo.com/?q=%22generative+art+appreciation%22), ["appreciating generative art"](https://duckduckgo.com/?q=%22appreciating+generative+art%22), ["generative literature appreciation"](https://duckduckgo.com/?q=%22generative+literature+appreciation%22), ["appreciating generative literature"](https://duckduckgo.com/?q=%22appreciating+generative+literature%22), ["electronic literature appreciation"](https://duckduckgo.com/?q=%22electronic+literature+appreciation%22), and ["appreciating electronic literature"](https://duckduckgo.com/?q=%22appreciating+electronic+literature%22).

So, it would seem, maybe these resources are kind of scarce, and maybe that's understandable because it's a relatively new field.   But also, since you represent an entire community that does this sort of thing, maybe you would know of some of these resources?

Thanks!

**Comment by MichaelPaulukonis** [comment]
I think he meant "appreciates" as in "rise in value of price."

Instead of being VCs -- Venture Capitalists -- they are LCs - Literary Capitalists -- and they are pumping a disruptive market for increased ROI, and NaNoGenMo is an Incubator. You signed your NDA prior to the [seed-round](https://github.com/catseye/seedbank), right?

![redress](https://cloud.githubusercontent.com/assets/2607898/11532853/a4fd776e-98d4-11e5-8a04-70aca6716e9a.gif)

---

In other news, I wish I could go as an angel investor.

**Comment by enkiv2** [comment]
Well, NaNoGenMo makes sense as an incubator until the spambot industry
decides to pivot. We can't compete with high-quality spampoetry like that!

**Comment by greg-kennedy** [comment]
The only way to give a speech on this is to have it randomly generated, of course.

BTW, I did give a totally straight-faced presentation at work on the merits of #144 - an attempt to cut costs by eliminating our legal department: [AutoLawyer.pptx](https://github.com/dariusk/NaNoGenMo-2015/files/49873/AutoLawyer.pptx)

**Comment by leonardoflores** [comment]
LOL. I meant "appreciate" in the cultural sense of the term, though monetary value can certainly accrue as the cultural capital of the works grows.

There is a large international and growing community of scholars and practitioners who study, publish, review, and exhibit electronic literature. The ELO is the oldest and largest active academic community dedicated to this emergent literary form. (See http://eliterature.org). In addition to the yearly conferences and other initiatives, the ELO publishes elit collections every 5 years (see http://collection.eliterature.org).

BTW, the next one will be published in January 2014 and as one of the editors I solicited NaNoGenMo submissions last year.

I, like many other ELO members, research, teach, write about, present, and occasionally create e-literature. I have a resource called I ❤️ E-Poetry where you can see some of my research: http://iloveepoetry.com

**Comment by leonardoflores** [comment]
Greg, I really like the idea of a generated presentation!

A format which might work nicely for a NaNoGenMo panel is a round table in which 5-6 persons give artist talks about the novels they generated. Basically the write ups I see here with a sampling from the generated texts.

**Comment by enkiv2** [comment]
How about a format wherein 5-6 people in a round-table panel ostensibly
discuss the novels they generated but are actually cyranoids reading off
pre-generated scripts written by robots? And then we poll the audience to
figure out how long it took them to notice.

**Comment by enkiv2** [comment]
Because the long arc of academic conference format swings toward
performance art.

**Comment by leonardoflores** [comment]
A direct outcome of attending this conference is that the community of academics may start teaching your work.

There are many courses out there, a notable recent example is Mark Sample's EdX course on Electronic Literature (https://www.edx.org/course/electronic-literature-davidsonx-d004x). I have been teaching the subject since 2003. My most recent course to do so is my Introduction to Poetry class (http://leonardoflores.net/3279)

**Comment by leonardoflores** [comment]
Such a format would be super cool and welcomed, enkiv2. :-)

**Comment by leonardoflores** [comment]
Folks, for full disclosure purposes, you should know that I'm an ELO board member. I serve as the Treasurer for the organization and am in charge of coordinating archiving and preservation projects.

So don't hesitate to ask any questions about the  organization or conference.

My blog: http://leonardoflores.net

**Comment by enkiv2** [comment]
I wasn't being wholly serious. While I would certainly watch such a talk
(in fact, if you upload videos of presentations after the conference, I
will definitely watch them), flying to Australia is not in the cards for me
-- even with seven months advance warning. Sorry! Maybe some of the people
on the list whose work proper is in the field of generative text will be
more likely to swing it, particularly the academics, since some university
departments are happy to pay for conferences & transportation.

**Comment by ikarth** [comment]
I'd be up for participating in a round table.

**Comment by leonardoflores** [comment]
Quick clarification: it's Victoria in Canada.

And yes there are some expenses to be considered. https://www.regonline.ca/Register/Checkin.aspx?EventID=1769849

**Comment by MichaelPaulukonis** [comment]
>  I serve as the Treasurer for the organization

FOLLOW THE MONEY

**Comment by leonardoflores** [comment]
I wish we had money...

The registration fees all go to cover conference costs and the organization itself is funded by membership fees, which are quite low, compared to other organizations. The board of directors is purely voluntary and we don't get any fee waivers, travel bursaries, or any kind of monetary compensation. 

We're as nonprofit as it gets. :-)
